public: false
type: "docs"
category: 
- "preservation"
- "collection development and management"
tags:
    - "policy"
title: Valuable/Vulnerable Materials Policy
description: This policy details the process by which archival documents, fine arts objects, and other collection items in the RAC's possession are identified as valuable/vulnerable.
pages:
  - ["Valuable/Vulnerable Materials Policy", "index"]
